"""
Database models and helpers for the Wellness Coach application.
Stores daily habits, wellness plans, check-ins, and analytics data.
"""

import json
import os
from datetime import datetime, timedelta
from typing import Any

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    String,
    Text,
    create_engine,
)
from sqlalchemy.orm import Session, declarative_base, sessionmaker

Base = declarative_base()


class DailyHabitLog(Base):
    """Stores daily habit entries (sleep, exercise, nutrition, mood)."""

    __tablename__ = "daily_habit_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(255), nullable=False, index=True)
    date = Column(DateTime, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Sleep metrics
    sleep_hours = Column(Float, nullable=True)
    sleep_quality = Column(Integer, nullable=True)  # 1-10 scale
    bedtime = Column(String(50), nullable=True)  # e.g., "22:30"
    wake_time = Column(String(50), nullable=True)  # e.g., "07:00"

    # Exercise metrics
    exercise_type = Column(
        String(100), nullable=True
    )  # e.g., "Running", "Yoga", "Strength"
    exercise_duration_minutes = Column(Integer, nullable=True)
    exercise_intensity = Column(String(50), nullable=True)  # Low, Medium, High
    steps = Column(Integer, nullable=True)

    # Nutrition metrics
    meals_logged = Column(Integer, default=0)
    water_intake_liters = Column(Float, nullable=True)
    calories_consumed = Column(Integer, nullable=True)
    nutrition_notes = Column(Text, nullable=True)

    # Mood metrics
    mood_score = Column(Integer, nullable=True)  # 1-10 scale
    energy_level = Column(Integer, nullable=True)  # 1-10 scale
    stress_level = Column(Integer, nullable=True)  # 1-10 scale
    mood_notes = Column(Text, nullable=True)

    # Additional notes
    general_notes = Column(Text, nullable=True)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "userId": self.user_id,
            "date": self.date.isoformat() if self.date else None,
            "createdAt": self.created_at.isoformat() if self.created_at else None,
            "sleep": {
                "hours": self.sleep_hours,
                "quality": self.sleep_quality,
                "bedtime": self.bedtime,
                "wakeTime": self.wake_time,
            },
            "exercise": {
                "type": self.exercise_type,
                "durationMinutes": self.exercise_duration_minutes,
                "intensity": self.exercise_intensity,
                "steps": self.steps,
            },
            "nutrition": {
                "mealsLogged": self.meals_logged,
                "waterIntakeLiters": self.water_intake_liters,
                "caloriesConsumed": self.calories_consumed,
                "notes": self.nutrition_notes,
            },
            "mood": {
                "score": self.mood_score,
                "energyLevel": self.energy_level,
                "stressLevel": self.stress_level,
                "notes": self.mood_notes,
            },
            "generalNotes": self.general_notes,
        }


class WellnessPlan(Base):
    """Stores personalized wellness plans generated by LangGraph."""

    __tablename__ = "wellness_plans"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(255), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    week_number = Column(Integer, default=1)

    # Plan content
    focus_areas = Column(Text)  # JSON array of focus areas
    daily_goals = Column(Text)  # JSON object with daily goals
    weekly_objectives = Column(Text)  # JSON array
    plan_markdown = Column(Text)  # Full plan in markdown
    interventions = Column(Text)  # JSON array of suggested interventions

    # Status
    is_active = Column(Boolean, default=True)
    completed_at = Column(DateTime, nullable=True)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "userId": self.user_id,
            "createdAt": self.created_at.isoformat() if self.created_at else None,
            "weekNumber": self.week_number,
            "focusAreas": json.loads(self.focus_areas) if self.focus_areas else [],
            "dailyGoals": json.loads(self.daily_goals) if self.daily_goals else {},
            "weeklyObjectives": (
                json.loads(self.weekly_objectives) if self.weekly_objectives else []
            ),
            "planMarkdown": self.plan_markdown,
            "interventions": (
                json.loads(self.interventions) if self.interventions else []
            ),
            "isActive": self.is_active,
            "completedAt": self.completed_at.isoformat() if self.completed_at else None,
        }


class WeeklyCheckIn(Base):
    """Stores weekly check-in assessments."""

    __tablename__ = "weekly_check_ins"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(255), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    week_start_date = Column(DateTime, nullable=False)

    # Assessment results
    assessment_markdown = Column(Text)  # Full assessment in markdown
    progress_summary = Column(Text)  # JSON object
    correlations_found = Column(Text)  # JSON array of correlations
    recommendations = Column(Text)  # JSON array

    # Metrics summary
    avg_sleep_hours = Column(Float, nullable=True)
    avg_mood_score = Column(Float, nullable=True)
    total_exercise_minutes = Column(Integer, nullable=True)
    avg_energy_level = Column(Float, nullable=True)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "userId": self.user_id,
            "createdAt": self.created_at.isoformat() if self.created_at else None,
            "weekStartDate": (
                self.week_start_date.isoformat() if self.week_start_date else None
            ),
            "assessmentMarkdown": self.assessment_markdown,
            "progressSummary": (
                json.loads(self.progress_summary) if self.progress_summary else {}
            ),
            "correlationsFound": (
                json.loads(self.correlations_found) if self.correlations_found else []
            ),
            "recommendations": (
                json.loads(self.recommendations) if self.recommendations else []
            ),
            "avgSleepHours": self.avg_sleep_hours,
            "avgMoodScore": self.avg_mood_score,
            "totalExerciseMinutes": self.total_exercise_minutes,
            "avgEnergyLevel": self.avg_energy_level,
        }


class Correlation(Base):
    """Stores identified correlations between habits."""

    __tablename__ = "correlations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(255), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Correlation details
    metric1 = Column(String(100), nullable=False)  # e.g., "sleep_hours"
    metric2 = Column(String(100), nullable=False)  # e.g., "mood_score"
    correlation_type = Column(String(50), nullable=False)  # positive, negative
    strength = Column(Float, nullable=False)  # 0.0 to 1.0
    description = Column(Text, nullable=True)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "userId": self.user_id,
            "createdAt": self.created_at.isoformat() if self.created_at else None,
            "metric1": self.metric1,
            "metric2": self.metric2,
            "correlationType": self.correlation_type,
            "strength": self.strength,
            "description": self.description,
        }


def get_engine():
    """Get SQLAlchemy engine for the wellness coach database."""
    db_path = (
        os.getenv("WELLNESS_SQLITE_PATH")
        or os.getenv("SQLITE_DB_PATH")
        or "./memori_wellness.sqlite"
    )
    database_url = f"sqlite:///{db_path}"
    return create_engine(
        database_url,
        pool_pre_ping=True,
        connect_args={"check_same_thread": False},
    )


def get_session() -> Session:
    """Get a new database session."""
    engine = get_engine()
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    return SessionLocal()


def init_database():
    """Initialize database tables."""
    engine = get_engine()
    Base.metadata.create_all(bind=engine)


# Analytics helpers
def get_habit_stats(db: Session, user_id: str, days: int = 30) -> dict[str, Any]:
    """Get statistics for habits over the last N days."""
    end_date = datetime.utcnow()
    start_date = end_date - timedelta(days=days)

    logs = (
        db.query(DailyHabitLog)
        .filter(
            DailyHabitLog.user_id == user_id,
            DailyHabitLog.date >= start_date,
        )
        .all()
    )

    if not logs:
        return {
            "totalDays": 0,
            "avgSleepHours": 0,
            "avgMoodScore": 0,
            "totalExerciseMinutes": 0,
            "avgEnergyLevel": 0,
            "avgStressLevel": 0,
        }

    sleep_hours = [log.sleep_hours for log in logs if log.sleep_hours is not None]
    mood_scores = [log.mood_score for log in logs if log.mood_score is not None]
    energy_levels = [log.energy_level for log in logs if log.energy_level is not None]
    stress_levels = [log.stress_level for log in logs if log.stress_level is not None]
    exercise_minutes = [
        log.exercise_duration_minutes
        for log in logs
        if log.exercise_duration_minutes is not None
    ]

    return {
        "totalDays": len(logs),
        "avgSleepHours": sum(sleep_hours) / len(sleep_hours) if sleep_hours else 0,
        "avgMoodScore": sum(mood_scores) / len(mood_scores) if mood_scores else 0,
        "totalExerciseMinutes": sum(exercise_minutes) if exercise_minutes else 0,
        "avgEnergyLevel": (
            sum(energy_levels) / len(energy_levels) if energy_levels else 0
        ),
        "avgStressLevel": (
            sum(stress_levels) / len(stress_levels) if stress_levels else 0
        ),
    }


def get_weekly_activity(db: Session, user_id: str, weeks: int = 12) -> list[dict]:
    """Get weekly habit activity for the last N weeks."""
    end_date = datetime.utcnow()
    start_date = end_date - timedelta(weeks=weeks)

    logs = (
        db.query(DailyHabitLog)
        .filter(
            DailyHabitLog.user_id == user_id,
            DailyHabitLog.date >= start_date,
        )
        .all()
    )

    # Group by week
    weekly_data: dict[str, dict] = {}
    for log in logs:
        week_start = log.date - timedelta(days=log.date.weekday())
        week_key = week_start.strftime("%Y-%m-%d")

        if week_key not in weekly_data:
            weekly_data[week_key] = {
                "sleepHours": [],
                "moodScores": [],
                "exerciseMinutes": [],
                "energyLevels": [],
            }

        if log.sleep_hours:
            weekly_data[week_key]["sleepHours"].append(log.sleep_hours)
        if log.mood_score:
            weekly_data[week_key]["moodScores"].append(log.mood_score)
        if log.exercise_duration_minutes:
            weekly_data[week_key]["exerciseMinutes"].append(
                log.exercise_duration_minutes
            )
        if log.energy_level:
            weekly_data[week_key]["energyLevels"].append(log.energy_level)

    # Calculate averages
    result = []
    for week_key, data in sorted(weekly_data.items()):
        result.append(
            {
                "week": week_key,
                "avgSleepHours": (
                    sum(data["sleepHours"]) / len(data["sleepHours"])
                    if data["sleepHours"]
                    else 0
                ),
                "avgMoodScore": (
                    sum(data["moodScores"]) / len(data["moodScores"])
                    if data["moodScores"]
                    else 0
                ),
                "totalExerciseMinutes": (
                    sum(data["exerciseMinutes"]) if data["exerciseMinutes"] else 0
                ),
                "avgEnergyLevel": (
                    sum(data["energyLevels"]) / len(data["energyLevels"])
                    if data["energyLevels"]
                    else 0
                ),
            }
        )

    return result
