import React, { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import { WellnessProfile } from "../types";

type Props = {
  apiBase: string;
  userId: string;
  profile: WellnessProfile;
  openaiKey?: string;
  memoriKey?: string;
};

function WellnessPlanTab({ apiBase, userId, profile, openaiKey, memoriKey }: Props) {
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [plan, setPlan] = useState<any>(null);
  const [planHistory, setPlanHistory] = useState<any[]>([]);

  useEffect(() => {
    if (userId) {
      loadActivePlan();
      loadPlanHistory();
    }
  }, [userId]);

  const loadActivePlan = async () => {
    try {
      const res = await fetch(`${apiBase}/plan/${userId}/active`);
      if (res.ok) {
        const data = await res.json();
        if (data.exists) {
          setPlan(data.plan);
        }
      }
    } catch (e) {
      // Ignore
    }
  };

  const loadPlanHistory = async () => {
    try {
      const res = await fetch(`${apiBase}/plan/${userId}/history?limit=5`);
      if (res.ok) {
        const data = await res.json();
        setPlanHistory(data.plans || []);
      }
    } catch (e) {
      // Ignore
    }
  };

  const generatePlan = async () => {
    setGenerating(true);
    setError(null);
    try {
      const res = await fetch(`${apiBase}/plan/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          userId,
          profile,
          openaiKey,
          memoriKey,
        })
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.detail ?? "Failed to generate plan");
      }
      const data = await res.json();
      setPlan({
        focusAreas: data.focusAreas,
        dailyGoals: data.dailyGoals,
        weeklyObjectives: data.weeklyObjectives,
        planMarkdown: data.planMarkdown,
        interventions: data.interventions,
      });
      await loadPlanHistory();
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      setError(msg);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="tab-panel">
      <h2>🎯 Wellness Plan</h2>
      <p style={{ marginBottom: "24px", color: "var(--color-text-secondary)" }}>
        Get personalized wellness plans generated by AI using LangGraph, tailored to your goals and habit history.
      </p>

      {!plan && (
        <div className="banner info">
          <p>No active wellness plan. Generate one to get started!</p>
          <button
            className="btn-primary"
            onClick={generatePlan}
            disabled={generating || !userId}
            style={{ marginTop: "16px" }}
          >
            {generating ? "Generating Plan..." : "Generate Wellness Plan"}
          </button>
        </div>
      )}

      {plan && (
        <section className="wellness-plan-section">
          <div className="plan-header">
            <h3>Active Wellness Plan</h3>
            <button
              className="btn-secondary"
              onClick={generatePlan}
              disabled={generating}
            >
              {generating ? "Generating..." : "Generate New Plan"}
            </button>
          </div>

          {plan.focusAreas && plan.focusAreas.length > 0 && (
            <div className="plan-section">
              <h4>Focus Areas</h4>
              <div className="focus-areas">
                {plan.focusAreas.map((area: string, idx: number) => (
                  <span key={idx} className="focus-badge">{area}</span>
                ))}
              </div>
            </div>
          )}

          {plan.dailyGoals && Object.keys(plan.dailyGoals).length > 0 && (
            <div className="plan-section">
              <h4>Daily Goals</h4>
              <ul className="goals-list">
                {Object.entries(plan.dailyGoals).map(([key, value]: [string, any]) => (
                  <li key={key}>
                    <strong>{key.charAt(0).toUpperCase() + key.slice(1)}:</strong> {value}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {plan.weeklyObjectives && plan.weeklyObjectives.length > 0 && (
            <div className="plan-section">
              <h4>Weekly Objectives</h4>
              <ul className="objectives-list">
                {plan.weeklyObjectives.map((obj: string, idx: number) => (
                  <li key={idx}>{obj}</li>
                ))}
              </ul>
            </div>
          )}

          {plan.interventions && plan.interventions.length > 0 && (
            <div className="plan-section">
              <h4>Recommended Interventions</h4>
              <div className="interventions-list">
                {plan.interventions.map((intervention: any, idx: number) => (
                  <div key={idx} className="intervention-card">
                    <div className="intervention-header">
                      <span className="intervention-type">{intervention.type}</span>
                    </div>
                    <p className="intervention-action">{intervention.action}</p>
                    {intervention.rationale && (
                      <p className="intervention-rationale">{intervention.rationale}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {plan.planMarkdown && (
            <div className="plan-section">
              <h4>Full Plan</h4>
              <div className="markdown-content">
                <ReactMarkdown>{plan.planMarkdown}</ReactMarkdown>
              </div>
            </div>
          )}
        </section>
      )}

      {planHistory.length > 0 && (
        <section className="plan-history-section">
          <h3>Plan History</h3>
          <div className="history-list">
            {planHistory.map((p: any) => (
              <div key={p.id} className="history-item">
                <div className="history-header">
                  <span>Week {p.weekNumber}</span>
                  <span className="history-date">
                    {new Date(p.createdAt).toLocaleDateString()}
                  </span>
                </div>
                {p.focusAreas && p.focusAreas.length > 0 && (
                  <div className="history-focus">
                    Focus: {p.focusAreas.join(", ")}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>
      )}

      {error && <div className="banner error">{error}</div>}
    </div>
  );
}

export default WellnessPlanTab;
